apiVersion: v1
kind: Secret
metadata:
  name: discord-mirror-env
type: Opaque
stringData:
  SOURCE_CHANNEL_ID: ""
  SOURCE_DISCORD_BOT_TOKEN: ""
  TARGET_CHANNEL_ID: ""
  TARGET_DISCORD_BOT_TOKEN: ""
